version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mahloan
    ports: ["3306:3306"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 30

  api:
    build: .
    environment:
      DATABASE_URL: mysql+pymysql://root:root@db:3306/mahloan
    depends_on:
      db:
        condition: service_healthy
    ports: ["8000:8000"]
    command: bash -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"
